version: '3.5'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - /var/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - api

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: always
    environment:
      - PORT=${PORT}
    ports:
      - '5000:5000'
    volumes:
      - ./src:/app/src
    depends_on:
      - db